# Game Recommendation System


### Loading libraries 

In [1]:
import pandas as pd
import numpy as np

### importing dataset from CSV file

In [2]:
ratings = pd.read_csv('ratings.csv')
games = pd.read_csv('games.csv')

In [3]:
ratings.head(15)

userId  gameId  rating  timestamp
0        1       1     4.0  964982703
1        1       3     4.0  964981247
2        1       6     4.0  964982224
3        1      47     5.0  964983815
4        1      50     5.0  964982931
5        1      70     3.0  964982400
6        1     101     5.0  964980868
7        1     110     4.0  964982176
8        1     151     5.0  964984041
9        1     157     5.0  964984100
10       1     163     5.0  964983650
11       1     216     5.0  964981208
12       1     223     3.0  964980985
13       1     231     5.0  964981179
14       1     235     4.0  964980908

In [4]:
games.head(15)

gameId                                           gameName
0        1                                                140
1        2                                         10,000,000
2        3                                        007 Legends
3        4                                          0RBITALIS
4        5  1... 2... 3... KICK IT! (Drop That Beat Like a...
5        6                                    10 Second Ninja
6        7                                  100% Orange Juice
7        8                                          1000 Amps
8        9                             12 Labours of Hercules
9       10          12 Labours of Hercules II The Cretan Bull
10      11              12 Labours of Hercules III Girl Power
11      12                                            15 Days
12      13                                       16 Bit Arena
13      14                                       16bit Trader
14      15                             1701 A.D. Gold Edition

In [5]:
game_ratings= pd.merge(games,ratings)
game_ratings.head(15)

gameId gameName  userId  rating   timestamp
0        1      140       1     4.0   964982703
1        1      140       5     4.0   847434962
2        1      140       7     4.5  1106635946
3        1      140      15     2.5  1510577970
4        1      140      17     4.5  1305696483
5        1      140      18     3.5  1455209816
6        1      140      19     4.0   965705637
7        1      140      21     3.5  1407618878
8        1      140      27     3.0   962685262
9        1      140      31     5.0   850466616
10       1      140      32     3.0   856736119
11       1      140      33     3.0   939647444
12       1      140      40     5.0   832058959
13       1      140      43     5.0   848993983
14       1      140      44     3.0   869251860

In [6]:
# pivot ratings into games features
user_data = game_ratings.pivot(index = 'userId', columns = 'gameId', values = 'rating').fillna(0)
user_data.head()

gameId  1     2     3     4     5     6     7     8     9     10    ...  5128  \
userId                                                              ...         
1        4.0   0.0   4.0   0.0   0.0   4.0   0.0   0.0   0.0   0.0  ...   0.0   
2        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
5        4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

gameId  5131  5134  5135  5136  5137  5139  5146  5147  5151  
userId                                                        
1        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 3719 columns]

In [7]:
# make a copy of train and test datasets
dummy_train = game_ratings.copy()
dummy_train['rating'] = dummy_train['rating'].apply(lambda x: 0 if x > 0 else 1)


In [8]:
# The games not rated by user is marked as 1 for prediction 
dummy_train = dummy_train.pivot(index = 'userId', columns = 'gameId', values = 'rating').fillna(1)

# The games not rated by user is marked as 0 for evaluation 


In [9]:
dummy_train.head()

gameId  1     2     3     4     5     6     7     8     9     10    ...  5128  \
userId                                                              ...         
1        0.0   1.0   0.0   1.0   1.0   0.0   1.0   1.0   1.0   1.0  ...   1.0   
2        1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...   1.0   
3        1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...   1.0   
4        1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...   1.0   
5        0.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...   1.0   

gameId  5131  5134  5135  5136  5137  5139  5146  5147  5151  
userId                                                        
1        1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  
2        1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  
3        1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  
4        1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  
5        1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  

[5 rows x 3719 columns]

### using cosine similarity

In [10]:
from sklearn.metrics.pairwise import cosine_similarity

# User Similarity Matrix using Cosine similarity as a similarity measure between Users
user_similarity = cosine_similarity(user_data)
user_similarity[np.isnan(user_similarity)] = 0
print(user_similarity)

[[1.         0.07559644 0.08724532 ... 0.34824342 0.09357193 0.26621032]
 [0.07559644 1.         0.         ... 0.10518599 0.0763793  0.04967766]
 [0.08724532 0.         1.         ... 0.03692606 0.         0.0599236 ]
 ...
 [0.34824342 0.10518599 0.03692606 ... 1.         0.14594141 0.43025146]
 [0.09357193 0.0763793  0.         ... 0.14594141 1.         0.09750267]
 [0.26621032 0.04967766 0.0599236  ... 0.43025146 0.09750267 1.        ]]


In [11]:
similarity_matrix = pd.DataFrame(user_similarity)
similarity_matrix.head()

0         1         2         3         4         5         6    \
0  1.000000  0.075596  0.087245  0.194395  0.129080  0.128152  0.211084   
1  0.075596  1.000000  0.000000  0.010324  0.046036  0.070195  0.023682   
2  0.087245  0.000000  1.000000  0.003289  0.007333  0.005751  0.000000   
3  0.194395  0.010324  0.003289  1.000000  0.128659  0.088491  0.153076   
4  0.129080  0.046036  0.007333  0.128659  1.000000  0.300349  0.144063   

        7         8         9    ...       600       601       602       603  \
0  0.136968  0.087377  0.044345  ...  0.128546  0.164455  0.221701  0.070669   
1  0.075526  0.000000  0.130413  ...  0.242846  0.046733  0.033274  0.000000   
2  0.007219  0.000000  0.000000  ...  0.006538  0.007147  0.036546  0.000000   
3  0.062969  0.015447  0.081891  ...  0.137138  0.128273  0.308272  0.052985   
4  0.429075  0.000000  0.080440  ...  0.108589  0.418747  0.110255  0.258773   

        604       605       606       607       608       609  
0  0.208412  0.206733  0.269389  0.348243  0.093572  0.266210  
1  0.000000  0.057829  0.035877  0.105186  0.076379  0.049678  
2  0.021195  0.022417  0.028118  0.036926  0.000000  0.059924  
3  0.114749  0.252317  0.131746  0.179277  0.032198  0.197262  
4  0.201810  0.134012  0.152866  0.162143  0.261232  0.111363  

[5 rows x 610 columns]

### Predicting the user rating

In [12]:
user_predicted_ratings = np.dot(user_similarity, user_data)
user_predicteed_rating_matrix = pd.DataFrame(user_predicted_ratings)
user_predicteed_rating_matrix

0           1          2         3          4           5     \
0    175.645689   83.535516  38.028522  2.312349  25.295159   96.402712   
1     54.744455   25.541310   8.381968  0.810178   7.015990   26.985114   
2     16.309292    8.256403   4.436108  0.207086   2.341813   11.596744   
3    118.147783   51.780301  21.950055  1.842156  17.043936   59.984565   
4    149.740015   77.479339  29.650939  4.564325  29.488684   71.901547   
..          ...         ...        ...       ...        ...         ...   
605  164.611145   77.094457  30.461672  2.906572  22.833538   84.774732   
606  171.363800   81.476717  33.084993  2.783494  24.908106   87.808272   
607  232.679398  118.999609  49.044674  3.216626  36.169689  123.756409   
608  131.031996   67.254385  26.489998  3.506464  24.829878   62.682044   
609  196.334937   89.289901  33.838999  2.160010  25.007070  109.649982   

          6         7         8           9     ...       3709      3710  \
0    28.280174  4.356269  6.968041   99.591395  ...   8.038230  2.076405   
1     7.404926  1.193770  1.570430   30.736301  ...   1.169885  0.470169   
2     3.122505  0.618724  0.717439    9.285644  ...   1.170610  0.304107   
3    21.755626  2.658097  3.720572   60.440312  ...   5.226019  1.631351   
4    33.434937  5.418694  6.056016   98.586407  ...   3.763517  0.802913   
..         ...       ...       ...         ...  ...        ...       ...   
605  29.944546  3.961485  5.078888   86.406295  ...   8.030655  2.588018   
606  28.714537  4.388068  7.248933  100.181991  ...   6.704602  1.629557   
607  39.955529  6.593499  9.996365  139.961478  ...  11.431653  3.306251   
608  27.706823  4.210107  6.556478  101.956047  ...   3.140941  0.759903   
609  27.881857  4.638982  6.892108  107.493361  ...  10.297240  2.815509   

         3711       3712      3713      3714       3715       3716      3717  \
0    2.262713   9.710295  1.493714  3.252045   8.590318   7.582829  3.439533   
1    0.311593   2.445309  0.277785  0.480845   2.107050   1.763420  0.849259   
2    0.414708   0.973149  0.323351  0.414408   1.100907   0.942746  0.268585   
3    1.409238  10.600400  1.091606  2.744722   6.673034   5.505280  3.912814   
4    0.917512   5.853478  0.585975  1.387162   3.861847   3.739377  1.763273   
..        ...        ...       ...       ...        ...        ...       ...   
605  2.071660  17.172760  1.656539  3.678848  11.640892   7.938958  5.218258   
606  1.859008   9.247782  1.349575  2.395056   7.084850   6.510983  2.953034   
607  3.177303  13.607158  2.329996  4.433755  12.411553  13.329820  4.634894   
608  0.684837   3.796159  0.546153  0.942664   3.142013   3.216517  1.086549   
609  2.505476  11.941681  4.158384  3.878068  13.369621  12.011966  4.714683   

          3718  
0    14.882391  
1     4.163632  
2     1.501895  
3     9.580191  
4     7.386538  
..         ...  
605  14.104429  
606  12.917273  
607  22.405654  
608   6.235537  
609  17.863161  

[610 rows x 3719 columns]

### Removing already rated games

In [13]:
user_final_ratings = np.multiply(user_predicted_ratings, dummy_train)
user_final_ratings.head()
#to remove already rated games by users

gameId        1          2          3         4          5          6     \
userId                                                                     
1         0.000000  83.535516   0.000000  2.312349  25.295159   0.000000   
2        54.744455  25.541310   8.381968  0.810178   7.015990  26.985114   
3        16.309292   8.256403   4.436108  0.207086   2.341813  11.596744   
4       118.147783  51.780301  21.950055  1.842156  17.043936  59.984565   
5         0.000000  77.479339  29.650939  4.564325  29.488684  71.901547   

gameId       7         8         9          10    ...      5128      5131  \
userId                                            ...                       
1       28.280174  4.356269  6.968041  99.591395  ...  8.038230  2.076405   
2        7.404926  1.193770  1.570430  30.736301  ...  1.169885  0.470169   
3        3.122505  0.618724  0.717439   9.285644  ...  1.170610  0.304107   
4       21.755626  2.658097  3.720572  60.440312  ...  5.226019  1.631351   
5       33.434937  5.418694  6.056016  98.586407  ...  3.763517  0.802913   

gameId      5134       5135      5136      5137      5139      5146      5147  \
userId                                                                          
1       2.262713   9.710295  1.493714  3.252045  8.590318  7.582829  3.439533   
2       0.311593   2.445309  0.277785  0.480845  2.107050  1.763420  0.849259   
3       0.414708   0.973149  0.323351  0.414408  1.100907  0.942746  0.268585   
4       1.409238  10.600400  1.091606  2.744722  6.673034  5.505280  3.912814   
5       0.917512   5.853478  0.585975  1.387162  3.861847  3.739377  1.763273   

gameId       5151  
userId             
1       14.882391  
2        4.163632  
3        1.501895  
4        9.580191  
5        7.386538  

[5 rows x 3719 columns]

### Recommending games


In [14]:
try:
    user_input=input('Enter Game Name on which recommendation are to be made:')
    # 15 Days input as user_input
    inp=games[games['gameName']==user_input].index.tolist()
    inp=inp[0]
    games['rating']=user_final_ratings.iloc[inp]
    games.head(5)
    print('Your Top 5 recommended games are\n', games.sort_values(["rating"],ascending=False)[0:5])
except:
    print('sorry the game is not in dataset')


Enter Game Name on which recommendation are to be made:15 Days
Your Top 5 recommended games are
       gameId                     gameName     rating
356      357  Assassin's Creed Liberation  55.962220
318      319                       Arma 2  48.849390
296      297                         APOX  46.288107
593      594                   BloodRayne  42.648043
2571    2572  Lovely Weather We're Having  39.253529
